### ISSUE TITLE
Encountering issue "can't find package tclreadline" after installing tclreadline on Linux

### ISSUE THREAD

**Issue by MikeNana** [flightaware/tclreadline#49] opened 2023-03-01 10:04 UTC

**Comment by resuna** [comment] 2023-03-01 10:28
Where did you install it? Does your auto_path go through that location? Did you run autoconf and configure?

**Comment by MikeNana** [comment] 2023-03-02 01:46
> Where did you install it? Does your auto_path go through that location? Did you run autoconf and configure?

I installed it on centos 7 system and under my $HOME directory, and the install commands are "./configure --with-tcl=/usr/lib64/tcl8.5 --with-tk=/usr/lib64/; make; make install". What do you mean about auto_path? Where should I set the auto_path? Thx for your suggestion.

**Comment by MikeNana** [comment] 2023-03-02 01:54
> Where did you install it? Does your auto_path go through that location? Did you run autoconf and configure?

**Comment by MikeNana** [comment] 2023-03-02 02:19
> Where did you install it? Does your auto_path go through that location? Did you run autoconf and configure?

When I ran tclsh after copying sample.tclshrc into my work directory, I got "can't read "0": no such variable" issue.

**Comment by MikeNana** [comment] 2023-03-02 03:19
> Where did you install it? Does your auto_path go through that location? Did you run autoconf and configure?

I've set auto_path by using command "set auto_path [linsert $auto_path 0 /usr/lib/tclreadline2.3.8]" in tclsh, but still got "can't find package tclreadline" error.

**Comment by resuna** [comment] 2023-03-02 15:57
Did it actually install it there? Is there a pkgIndex.tcl file there? What happens if you run the commands in there manually after expansion... that should be `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl`?

**Comment by MikeNana** [comment] 2023-03-03 02:11
> 

There are some errors "command not found" like the pic shows after running the command `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl`. 
![1677808900751](https://user-images.githubusercontent.com/37776951/222613809-b2b7035b-295f-45a1-bfad-c3425d1364cf.png)

**Comment by resuna** [comment] 2023-03-03 03:26
You appear to be attempting to source the file using bash.
It's not bash commands, it's tcl commands, you need to run tclsh and source it from there.

**Comment by MikeNana** [comment] 2023-03-03 03:37
> 
There are some errors "command not found" like the pic shows after running the command `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl` .
![1677808900751](https://user-images.githubusercontent.com/37776951/222612741-ec2f4cf4-5ce5-40f4-8c2c-979d3a6647ce.png)


> You appear to be attempting to source the file using bash. It's not bash commands, it's tcl commands, you need to run tclsh and source it from there.
When I launched tclsh and ran the command `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl` again, the result is like the pic shows.

![1677814585191](https://user-images.githubusercontent.com/37776951/222625360-545d27bd-4bbc-4ad3-ae8e-c709aba13c7b.png)

**Comment by MikeNana** [comment] 2023-03-03 03:38
> You appear to be attempting to source the file using bash. It's not bash commands, it's tcl commands, you need to run tclsh and source it from there.

When I launched tclsh and ran the command source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl again, the result is like the pic shows.
![1677814585191](https://user-images.githubusercontent.com/37776951/222625474-5ee6806a-19f3-4bf0-af61-51c1c28be59f.png)

**Comment by resuna** [comment] 2023-03-03 03:50
You appear to have already loaded tclreadline from your .tclshrc, then, because that's where the previous instance of _unknown would be coming from.

Remove your .tclshrc (the one you copied from sample.tclshrc)

Then you can test this a straight tclsh without any customization.

At that point, start up tclsh, and do "package require tclreadline".

If that fails, we can investigate why.

If that succeeds, do "tclreadline::Loop"

What does your .tclshrc look like now?

**Comment by MikeNana** [comment] 2023-03-03 04:30
>


> You appear to have already loaded tclreadline from your .tclshrc, then, because that's where the previous instance of _unknown would be coming from.
> 
> Remove your .tclshrc (the one you copied from sample.tclshrc)
> 
> Then you can test this a straight tclsh without any customization.
> 
> At that point, start up tclsh, and do "package require tclreadline".
> 
> If that fails, we can investigate why.
> 
> If that succeeds, do "tclreadline::Loop"
> 
> What does your .tclshrc look like now?

This is what my .tclshrc look like now. 
![1677817680310](https://user-images.githubusercontent.com/37776951/222631585-cecd4017-a33e-491b-8ac2-095a49a9d2f0.png)

And when I do "package require tclreadline" in tclsh, I got "can't find package tclreadline" error again.
![1677817820936](https://user-images.githubusercontent.com/37776951/222631735-f578fb1a-8e04-4d18-bab8-2d287d5ad4a2.jpg)

**Comment by resuna** [comment] 2023-03-03 11:20
Is that after removing your .tclshrc?

And what happens when you `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl` after removing your .tclshrc?

**Comment by MikeNana** [comment] 2023-03-06 01:45
> Is that after removing your .tclshrc?
> 
> And what happens when you `source /usr/lib/tclreadline2.3.8/tclreadlineInit.tcl` after removing your .tclshrc?

When I removed .tclshrc, the result was as follows.
![1678067109066](https://user-images.githubusercontent.com/37776951/223001259-a18f35f6-dbca-4c0f-8088-6d446d910178.png)

**Comment by resuna** [comment] 2023-03-06 02:42
That's returned from the set statement at the end of the file.

But does `tclreadline::Loop` work?

Also, you don't need to insert the results as images, it makes it hard for me to follow, you can just

> quote it

Or

`Insert it as code`

**Comment by MikeNana** [comment] 2023-03-06 05:42
> That's returned from the set statement at the end of the file.
> 
> But does `tclreadline::Loop` work?
> 
> Also, you don't need to insert the results as images, it makes it hard for me to follow, and I can't copy and paste text from pictures... you can just
> 
> > quote it
> 
> Or
> 
> `Insert it as code`

I've launched tclreadline after doing `tclreadline::Loop`, thanks for your guiding !!!

**Comment by MikeNana** [comment] 2023-03-06 08:29
> That's returned from the set statement at the end of the file.
> 
> But does `tclreadline::Loop` work?
> 
> Also, you don't need to insert the results as images, it makes it hard for me to follow, and I can't copy and paste text from pictures... you can just
> 
> > quote it
> 
> Or
> 
> `Insert it as code`

But I don't know why the .tclshrc didn't work, maybe you can help check it out.

**Comment by resuna** [comment] 2023-03-06 13:44
This is checking it out. I can't reproduce it, so it's something in your setup that's the difference. And you seem to be using quite an old version of Tcl, 8.5. Tcl 8.6 was released over a decade ago.

**Comment by bovine** [comment] 2023-06-01 19:41
closing based on resuna's last message and no further response.

**Closed by bovine** 2023-06-01 19:41 UTC
